//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFollowup
    {
        public int FollowUpId { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<int> FollowupType { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> NextFollowUpDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
